version: '2.0'
services:
  server:
    image: docker.pkg.github.com/capstoneris/css-backend/css-backend:master
    environment:
      - DATABASE_HOST=database
    ports:
      - "8081:8081"
      - "8082:8082"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=css-db
      - POSTGRES_USER=css-db
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
