version: '2.0'
services:
  server:
    image: docker.pkg.github.com/capstoneris/css-backend/css-backend:master
    ports:
      - "8081:8081"
  database:
    image: docker.pkg.github.com/capstoneris/css-backend/css-database:latest
    ports:
      - "5432:5432"
